AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LinkedIn Advanced Search Backend - SAM Template with RAGStack Integration

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
  IncludeDevOrigins:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  ProductionOrigins:
    Type: String
    Default: ''
    Description: Comma-separated production origins for CORS (Lambda env vars)
  ProductionOrigin:
    Type: String
    Default: ''
    Description: Primary production origin for S3 CORS (e.g., https://myapp.com)
  OpenAIApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: OpenAI API key for LLM Lambda
  BedrockModelId:
    Type: String
    Default: us.meta.llama3-2-90b-instruct-v1:0
    Description: Bedrock model ID for LLM operations
  # RAGStack Integration - Nested Stack (recommended)
  DeployRAGStack:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Deploy RAGStack as nested stack (true) or use external endpoint (false)
  AdminEmail:
    Type: String
    Default: ''
    Description: Admin email for RAGStack deployment (required if DeployRAGStack=true)
    AllowedPattern: '^([\w.+-]+@([\w-]+\.)+[\w-]{2,6})?$'
  # RAGStack Integration - External Endpoint (alternative to nested deployment)
  RagstackGraphqlEndpoint:
    Type: String
    Default: ''
    Description: External RAGStack GraphQL endpoint (used only if DeployRAGStack=false)
  RagstackApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: External RAGStack API key (used only if DeployRAGStack=false)

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Layers:
      - !Ref SharedPythonLayer
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref ProfilesTable
        LOG_LEVEL: INFO
        ALLOWED_ORIGINS: !If
          - IncludeDevOriginsCondition
          - !Sub 'http://localhost:5173,http://localhost:3000${ProductionOrigins}'
          - !Ref ProductionOrigins

Conditions:
  IncludeDevOriginsCondition: !Equals [!Ref IncludeDevOrigins, 'true']
  HasProductionOrigin: !Not [!Equals [!Ref ProductionOrigin, '']]
  DeployRAGStackCondition: !Equals [!Ref DeployRAGStack, 'true']

Resources:
  # Shared Python Layer for common code (errors, utils, services)
  SharedPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'linkedin-shared-python-${Environment}'
      Description: Shared Python utilities for LinkedIn Advanced Search Lambdas
      ContentUri: lambdas/shared/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  # RAGStack-Lambda Nested Stack for semantic search and profile ingestion
  RAGStackNestedStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployRAGStackCondition
    Properties:
      TemplateURL: https://ragstack-quicklaunch-public-631094035453.s3.us-east-1.amazonaws.com/ragstack-template.yaml
      Parameters:
        StackPrefix: !Sub 'linkedin-ragstack-${Environment}'
        AdminEmail: !Ref AdminEmail
        BuildDashboard: 'true'
        BuildWebComponent: 'true'
      TimeoutInMinutes: 60
      Tags:
        - Key: Application
          Value: linkedin-advanced-search
        - Key: Environment
          Value: !Ref Environment

  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'linkedin-advanced-search-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ScreenshotBucket:
    Type: AWS::S3::Bucket
    DependsOn: S3ToSQSQueuePolicy
    Properties:
      BucketName: !Sub 'linkedin-screenshots-${AWS::AccountId}-${AWS::Region}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins: !If
              - HasProductionOrigin
              - !If
                - IncludeDevOriginsCondition
                - - 'http://localhost:5173'
                  - 'http://localhost:3000'
                  - !Ref ProductionOrigin
                - - !Ref ProductionOrigin
              - - 'http://localhost:5173'
                - 'http://localhost:3000'
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ProfileProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: linkedin-profiles/

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'linkedin-advanced-search-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'linkedin-advanced-search-client-${Environment}'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 4
      IdTokenValidity: 4
      RefreshTokenValidity: 30

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins: !If
          - HasProductionOrigin
          - !If
            - IncludeDevOriginsCondition
            - - http://localhost:5173
              - http://localhost:3000
              - !Ref ProductionOrigin
            - - !Ref ProductionOrigin
          - - http://localhost:5173
            - http://localhost:3000
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
              audience:
                - !Ref UserPoolClient

  EdgeProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'linkedin-edge-processing-${Environment}'
      CodeUri: lambdas/edge-processing/
      Handler: lambda_function.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          RAGSTACK_GRAPHQL_ENDPOINT: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.GraphQLApiUrl
            - !Ref RagstackGraphqlEndpoint
          RAGSTACK_API_KEY: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.ApiKey
            - !Ref RagstackApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        EdgeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /edges
            Method: POST
        EdgeOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /edges
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        RagstackApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /ragstack
            Method: POST
        RagstackOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /ragstack
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  DynamoDBApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'linkedin-dynamodb-api-${Environment}'
      CodeUri: lambdas/dynamodb-api/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_REGION: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        DynamoDBGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: GET
        DynamoDBPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: POST
        DynamoDBOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        ProfileGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: GET
        ProfilePost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: POST
        ProfileOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  ProfileProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'linkedin-profile-processing-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  ProfileProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'linkedin-profile-processing-queue-${Environment}'
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProfileProcessingDLQ.Arn
        maxReceiveCount: 3

  ProfileProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'linkedin-profile-processing-${Environment}'
      CodeUri: lambdas/profile-processing/
      Handler: lambda_function.lambda_handler
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          AI_MODEL_ID: !Ref BedrockModelId
          RAGSTACK_GRAPHQL_ENDPOINT: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.GraphQLApiUrl
            - !Ref RagstackGraphqlEndpoint
          RAGSTACK_API_KEY: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.ApiKey
            - !Ref RagstackApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
        - S3ReadPolicy:
            BucketName: !Ref ScreenshotBucket
        - S3WritePolicy:
            BucketName: !Ref ScreenshotBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProfileProcessingQueue.Arn
            BatchSize: 1

  S3ToSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProfileProcessingFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt ProfileProcessingQueue.Arn

  S3ToSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProfileProcessingQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt ProfileProcessingQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::linkedin-screenshots-${AWS::AccountId}-${AWS::Region}'

  LLMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'linkedin-llm-${Environment}'
      CodeUri: lambdas/llm/
      Handler: lambda_function.lambda_handler
      Timeout: 90
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
      Events:
        LLMApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /llm
            Method: POST
        LLMOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /llm
            Method: OPTIONS
            Auth:
              Authorizer: NONE



Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref ProfilesTable
  ScreenshotBucketName:
    Description: S3 bucket for screenshots
    Value: !Ref ScreenshotBucket
  ProfileProcessingQueueUrl:
    Description: SQS queue URL for profile processing
    Value: !Ref ProfileProcessingQueue
  ProfileProcessingDLQUrl:
    Description: Dead letter queue URL for failed profile processing
    Value: !Ref ProfileProcessingDLQ
  # RAGStack Outputs (only available when DeployRAGStack=true)
  RAGStackGraphQLEndpoint:
    Condition: DeployRAGStackCondition
    Description: RAGStack GraphQL API endpoint for semantic search
    Value: !GetAtt RAGStackNestedStack.Outputs.GraphQLApiUrl
  RAGStackDashboardUrl:
    Condition: DeployRAGStackCondition
    Description: RAGStack Dashboard URL for document management
    Value: !GetAtt RAGStackNestedStack.Outputs.UIUrl
  RAGStackApiKey:
    Condition: DeployRAGStackCondition
    Description: RAGStack API key (retrieve from SSM Parameter Store)
    Value: !GetAtt RAGStackNestedStack.Outputs.ApiKeyParameter
