AWSTemplateFormatVersion: '2010-09-09'
Description: 'Edge Processing Lambda with API Gateway - Manages edges between users and profiles in DynamoDB'

Parameters:
  LambdaCodeS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  LambdaCodeS3Key:
    Type: String
    Description: S3 key (path) to the Lambda deployment package zip file

  CognitoUserPoolId:
    Type: String
    Default: ''
    Description: (Optional) Cognito User Pool ID for JWT authentication

  CognitoUserPoolClientId:
    Type: String
    Default: ''
    Description: (Optional) Cognito User Pool Client ID for JWT authentication

  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name for resource naming and configuration

  DynamoDBTableName:
    Type: String
    Default: linkedin-advanced-search
    Description: Name of the DynamoDB table for profile and edge data

  LogRetentionDays:
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days

  ProjectName:
    Type: String
    Default: linkedin-advanced-search
    Description: Project name for resource naming and tagging

Mappings:
  EnvironmentConfig:
    dev:
      LambdaMemorySize: 512
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 100
      ApiThrottleRateLimit: 50
    staging:
      LambdaMemorySize: 512
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 200
      ApiThrottleRateLimit: 100
    prod:
      LambdaMemorySize: 1024
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 500
      ApiThrottleRateLimit: 250

Conditions:
  HasCognitoUserPool: !Not [!Equals [!Ref CognitoUserPoolId, ""]]

  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  # CloudWatch Log Group for Lambda
  EdgeProcessingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-edge-processing-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # IAM Role for Lambda Execution
  EdgeProcessingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # Lambda Function
  EdgeProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-edge-processing-${Environment}'
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt EdgeProcessingLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      MemorySize: !FindInMap [EnvironmentConfig, !Ref Environment, LambdaMemorySize]
      Timeout: !FindInMap [EnvironmentConfig, !Ref Environment, LambdaTimeout]
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      ReservedConcurrentExecutions: 10
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing
    DependsOn: EdgeProcessingLogGroup

  # API Gateway REST API
  EdgeProcessingApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-edge-processing-${Environment}-api'
      Description: 'API for edge processing operations'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # API Gateway Resource (proxy)
  EdgeProcessingApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ParentId: !GetAtt EdgeProcessingApi.RootResourceId
      PathPart: '{proxy+}'

  EdgeProcessingApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Condition: HasCognitoUserPool
    Properties:
      Name: !Sub '${ProjectName}-edge-processing-${Environment}-authorizer'
      RestApiId: !Ref EdgeProcessingApi
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}'

  EdgeProcessingApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ResourceId: !Ref EdgeProcessingApiResource
      HttpMethod: ANY
      AuthorizationType: !If [HasCognitoUserPool, COGNITO_USER_POOLS, NONE]
      AuthorizerId: !If [HasCognitoUserPool, !Ref EdgeProcessingApiAuthorizer, !Ref 'AWS::NoValue']
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EdgeProcessingLambda.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # API Gateway OPTIONS Method for CORS
  EdgeProcessingApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ResourceId: !Ref EdgeProcessingApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # API Gateway Deployment
  EdgeProcessingApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      StageName: !Sub '${Environment}-${AWS::StackName}'
    DependsOn:
      - EdgeProcessingApiMethod
      - EdgeProcessingApiOptionsMethod

  # Lambda Permission for API Gateway
  EdgeProcessingLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EdgeProcessingLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EdgeProcessingApi}/*/*/*'

  # CloudWatch Alarms
  EdgeProcessingLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-errors'
      AlarmDescription: 'Lambda function error rate alarm'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EdgeProcessingLambda
      TreatMissingData: notBreaching

  EdgeProcessingLambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-duration'
      AlarmDescription: 'Lambda function duration alarm'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EdgeProcessingLambda
      TreatMissingData: notBreaching

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL for edge processing'
    Value: !Sub 'https://${EdgeProcessingApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  LambdaFunctionArn:
    Description: 'Edge Processing Lambda function ARN'
    Value: !GetAtt EdgeProcessingLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: 'Edge Processing Lambda function name'
    Value: !Ref EdgeProcessingLambda
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  ApiId:
    Description: 'API Gateway REST API ID'
    Value: !Ref EdgeProcessingApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiId'