AWSTemplateFormatVersion: '2010-09-09'
Description: 'Edge Processing Lambda with API Gateway - Manages edges between users and profiles in DynamoDB'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name for resource naming and configuration

  DynamoDBTableName:
    Type: String
    Default: linkedin-advanced-search
    Description: Name of the DynamoDB table for profile and edge data

  LogRetentionDays:
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days

  ProjectName:
    Type: String
    Default: linkedin-advanced-search
    Description: Project name for resource naming and tagging

Mappings:
  EnvironmentConfig:
    dev:
      LambdaMemorySize: 512
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 100
      ApiThrottleRateLimit: 50
    staging:
      LambdaMemorySize: 512
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 200
      ApiThrottleRateLimit: 100
    prod:
      LambdaMemorySize: 1024
      LambdaTimeout: 30
      ApiThrottleBurstLimit: 500
      ApiThrottleRateLimit: 250

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  # CloudWatch Log Group for Lambda
  EdgeProcessingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-edge-processing-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # IAM Role for Lambda Execution
  EdgeProcessingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # Lambda Function
  EdgeProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-edge-processing-${Environment}'
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt EdgeProcessingLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          import base64
          import time
          from datetime import datetime, timezone
          from botocore.exceptions import ClientError

          # Configure logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          # Configuration from environment variables
          import os
          AWS_REGION = os.environ.get('AWS_REGION', 'us-west-2')
          DYNAMODB_TABLE_NAME = os.environ.get('DYNAMODB_TABLE_NAME', 'linkedin-advanced-search')

          # Initialize AWS clients
          dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION)
          table = dynamodb.Table(DYNAMODB_TABLE_NAME)

          def lambda_handler(event, context):
              """AWS Lambda handler for edge management"""
              try:
                  logger.info(f"Received event: {json.dumps(event)}")
                  
                  # Parse the request body
                  if 'body' in event:
                      if isinstance(event['body'], str):
                          body = json.loads(event['body'])
                      else:
                          body = event['body']
                  else:
                      body = event
                  
                  # Extract required parameters
                  linkedin_url = body.get('linkedinurl')
                  operation = body.get('operation', 'create')
                  updates = body.get('updates', {})
                  
                  if not linkedin_url:
                      return {
                          'statusCode': 400,
                          'headers': {
                              'Content-Type': 'application/json',
                              'Access-Control-Allow-Origin': '*',
                              'Access-Control-Allow-Headers': 'Content-Type,Authorization',
                              'Access-Control-Allow-Methods': 'POST,OPTIONS'
                          },
                          'body': json.dumps({
                              'error': 'Missing required parameter: linkedinurl'
                          })
                      }
                  
                  # Extract user ID from JWT token or use test user
                  user_id = event.get('requestContext', {}).get('authorizer', {}).get('claims', {}).get('sub')
                  if not user_id:
                      auth_header = event.get('headers', {}).get('Authorization', '')
                      if auth_header:
                          user_id = "test-user-id"
                      else:
                          return {
                              'statusCode': 401,
                              'headers': {
                                  'Content-Type': 'application/json',
                                  'Access-Control-Allow-Origin': '*',
                                  'Access-Control-Allow-Headers': 'Content-Type,Authorization',
                                  'Access-Control-Allow-Methods': 'POST,OPTIONS'
                              },
                              'body': json.dumps({
                                  'error': 'Unauthorized: Missing or invalid JWT token'
                              })
                          }
                  
                  # Simple edge creation logic (placeholder)
                  profile_id_b64 = base64.b64encode(linkedin_url.encode()).decode()
                  timestamp = datetime.now(timezone.utc).isoformat()
                  
                  # Create edge record
                  edge_data = {
                      'PK': f"USER#{user_id}",
                      'SK': f"PROFILE#{profile_id_b64}",
                      'status': updates.get('status', 'possible'),
                      'addedAt': timestamp,
                      'operation': operation
                  }
                  
                  table.put_item(Item=edge_data)
                  
                  return {
                      'statusCode': 200,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type,Authorization',
                          'Access-Control-Allow-Methods': 'POST,OPTIONS'
                      },
                      'body': json.dumps({
                          'message': f'Edge {operation} operation completed successfully',
                          'user_id': user_id,
                          'profile_id': f"PROFILE#{profile_id_b64}"
                      })
                  }
              
              except Exception as e:
                  logger.error(f"Unexpected error: {str(e)}")
                  return {
                      'statusCode': 500,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type,Authorization',
                          'Access-Control-Allow-Methods': 'POST,OPTIONS'
                      },
                      'body': json.dumps({
                          'error': 'Internal server error'
                      })
                  }
      MemorySize: !FindInMap [EnvironmentConfig, !Ref Environment, LambdaMemorySize]
      Timeout: !FindInMap [EnvironmentConfig, !Ref Environment, LambdaTimeout]
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          AWS_REGION: !Ref AWS::Region
      ReservedConcurrencyLimit: 10
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing
    DependsOn: EdgeProcessingLogGroup

  # API Gateway REST API
  EdgeProcessingApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-edge-processing-${Environment}-api'
      Description: 'API for edge processing operations'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # API Gateway Resource (proxy)
  EdgeProcessingApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ParentId: !GetAtt EdgeProcessingApi.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method (ANY)
  EdgeProcessingApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ResourceId: !Ref EdgeProcessingApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EdgeProcessingLambda.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # API Gateway OPTIONS Method for CORS
  EdgeProcessingApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      ResourceId: !Ref EdgeProcessingApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # API Gateway Deployment
  EdgeProcessingApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      StageName: !Ref Environment
    DependsOn:
      - EdgeProcessingApiMethod
      - EdgeProcessingApiOptionsMethod

  # API Gateway Stage
  EdgeProcessingApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref EdgeProcessingApi
      DeploymentId: !Ref EdgeProcessingApiDeployment
      StageName: !Ref Environment
      ThrottleSettings:
        BurstLimit: !FindInMap [EnvironmentConfig, !Ref Environment, ApiThrottleBurstLimit]
        RateLimit: !FindInMap [EnvironmentConfig, !Ref Environment, ApiThrottleRateLimit]
      TracingEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: edge-processing

  # Lambda Permission for API Gateway
  EdgeProcessingLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EdgeProcessingLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${EdgeProcessingApi}/*/*'

  # CloudWatch Alarms
  EdgeProcessingLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-errors'
      AlarmDescription: 'Lambda function error rate alarm'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EdgeProcessingLambda
      TreatMissingData: notBreaching

  EdgeProcessingLambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-edge-processing-${Environment}-lambda-duration'
      AlarmDescription: 'Lambda function duration alarm'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EdgeProcessingLambda
      TreatMissingData: notBreaching

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL for edge processing'
    Value: !Sub 'https://${EdgeProcessingApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  LambdaFunctionArn:
    Description: 'Edge Processing Lambda function ARN'
    Value: !GetAtt EdgeProcessingLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: 'Edge Processing Lambda function name'
    Value: !Ref EdgeProcessingLambda
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  ApiId:
    Description: 'API Gateway REST API ID'
    Value: !Ref EdgeProcessingApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiId'