AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LinkedIn Advanced Search - Serverless Stack

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref ProfilesTable
        DYNAMODB_TABLE_NAME: !Ref ProfilesTable
        LOG_LEVEL: INFO
  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - '*'
      AllowHeaders:
        - 'Content-Type'
        - 'Authorization'
      AllowMethods:
        - GET
        - POST
        - OPTIONS
      MaxAge: 600

Resources:
  # ===== DynamoDB Table =====
  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-profiles'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # ===== Lambda Functions =====
  EdgeProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-edge-processing'
      CodeUri: ../lambda-processing/linkedin-advanced-search-edge-processing-prod/
      Handler: lambda_function.lambda_handler
      Description: Edge processing for LinkedIn connections
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        EdgeApi:
          Type: HttpApi
          Properties:
            Path: /edge
            Method: POST

  DynamoDBApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-dynamodb-api'
      CodeUri: ../lambda-processing/linkedin-advanced-search-dynamodb-api-prod/
      Handler: lambda_function.lambda_handler
      Description: DynamoDB API operations
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        DynamoDBApi:
          Type: HttpApi
          Properties:
            Path: /dynamodb
            Method: POST

  PlaceholderSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-placeholder-search'
      Runtime: nodejs20.x
      CodeUri: ../lambda-processing/linkedin-advanced-search-placeholder-search-prod/
      Handler: index.handler
      Description: Placeholder search API
      Events:
        SearchApi:
          Type: HttpApi
          Properties:
            Path: /search
            Method: POST

  ProfileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-profile-api'
      CodeUri: ../lambda-processing/linkedin-advanced-search-profile-api-prod/
      Handler: lambda_function.lambda_handler
      Description: User profile management API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        GetProfile:
          Type: HttpApi
          Properties:
            Path: /profiles
            Method: GET
        UpdateProfile:
          Type: HttpApi
          Properties:
            Path: /profiles
            Method: POST

  # Implicit HttpApi created by SAM from events

  # ===== Cognito User Pool =====
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:5173
        - http://localhost:3000
      LogoutURLs:
        - http://localhost:5173
        - http://localhost:3000
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  # ===== S3 Buckets =====
  ScreenshotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-screenshots-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  EdgeEndpoint:
    Description: Edge processing endpoint
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/edge'

  SearchEndpoint:
    Description: Search endpoint
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/search'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  ScreenshotBucketName:
    Description: S3 bucket for screenshots
    Value: !Ref ScreenshotBucket
    Export:
      Name: !Sub '${AWS::StackName}-ScreenshotBucket'

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref ProfilesTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
