AWSTemplateFormatVersion: '2010-09-09'
Description: 'RAG-CloudStack: DynamoDB table (generic) for workflow/storage'

Parameters:
  ProjectName:
    Type: String
    Default: rag-cloudstack
  TableName:
    Type: String
    Default: rag-cloudstack-table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  TableName:
    Value: !Ref Table
    Export:
      Name: !Sub '${AWS::StackName}-TableName'


