AWSTemplateFormatVersion: '2010-09-09'
Description: 'RAG-CloudStack: S3 artifacts bucket for Lambda code (top-level lambdas/ prefix)'

Parameters:
  ProjectName:
    Type: String
    Default: rag-cloudstack
    Description: Project/stack name prefix for tagging
  ArtifactsBucketName:
    Type: String
    Description: Globally unique S3 bucket name to store Lambda artifacts

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  BucketName:
    Description: Artifacts bucket name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactsBucketName'


